### PyTorch

<center><img src="img/pytorch-logo.jpeg" width="800" /></center>

### What is PyTorch?

<center><img src="img/pytorch-logo.jpeg" width="400" /></center>

* open-source machine learning library written in Python, C++ and CUDA

* has NumPy-like interfaces

* provides two core features:
    * operations with tensors
    * automatic differentiation
    
    
* initialy developed at Facebook

https://pytorch.org

### What are tensors?

* Tensors are nothing but multidimensional arrays. 

<img src="img/tensor.jpeg" width="800">

### PyTorch Tensor operations - Vector

In [1]:
import torch

In [2]:
v = torch.tensor([3.5, 2.6, 7.1])

In [3]:
v

tensor([3.5000, 2.6000, 7.1000])

In [4]:
type(v)

torch.Tensor

In [5]:
v.shape

torch.Size([3])

### PyTorch Tensor operations - Matrix

In [6]:
m = torch.ones(3, 3)

In [7]:
m

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
m.shape

torch.Size([3, 3])

### Multiply matrix by vector

In [9]:
m = torch.rand(5, 5)

In [10]:
m

tensor([[0.9645, 0.8333, 0.3763, 0.7839, 0.6692],
        [0.2748, 0.7747, 0.9954, 0.1033, 0.3330],
        [0.8148, 0.9895, 0.7602, 0.9952, 0.6176],
        [0.2867, 0.8964, 0.1525, 0.7510, 0.0919],
        [0.6953, 0.5642, 0.2176, 0.1922, 0.3283]])

In [11]:
v = torch.rand(5, 1)

In [12]:
v

tensor([[0.0796],
        [0.2890],
        [0.1500],
        [0.8356],
        [0.0593]])

In [13]:
m * v

tensor([[0.0767, 0.0663, 0.0299, 0.0624, 0.0532],
        [0.0794, 0.2239, 0.2877, 0.0299, 0.0962],
        [0.1222, 0.1484, 0.1140, 0.1492, 0.0926],
        [0.2396, 0.7490, 0.1274, 0.6276, 0.0768],
        [0.0412, 0.0335, 0.0129, 0.0114, 0.0195]])

### Converting a PyTorch Tensor to a NumPy Array

In [14]:
a = torch.randn(10)

In [15]:
a

tensor([ 0.4183,  0.0478,  0.8503, -0.0604,  0.6550,  0.9678,  0.4597,  0.0293,
        -0.7070, -0.6939])

In [16]:
a.numpy()

array([ 0.41831252,  0.04776888,  0.8502592 , -0.06041376,  0.65495557,
        0.9677834 ,  0.4596742 ,  0.02927256, -0.70699877, -0.6939419 ],
      dtype=float32)

### Converting NumPy Array to PyTorch Tensor

In [17]:
import numpy as np

In [18]:
a = np.ones(7)
a

array([1., 1., 1., 1., 1., 1., 1.])

In [19]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)

### autograd.Variable

<center><img src="img/autograd-variable.png" width="400" /></center>

* part of **autograd** module of PyTorch
* simply a wraper around **torch.Tensor**
* are used to build computational graph
* automatically accumulate gradient w.r.t. this variable (can be controlled using **requires_grad** parameter)

### autograd.Variable

In [20]:
from torch.autograd import Variable

In [21]:
x = Variable(torch.ones(2, 2), requires_grad=True)

In [22]:
y = x + 100

In [23]:
z = 2 * (y ** 2)

In [24]:
z

tensor([[20402., 20402.],
        [20402., 20402.]], grad_fn=<MulBackward>)

In [25]:
out = torch.mean(z)

In [26]:
out

tensor(20402., grad_fn=<MeanBackward1>)

In [27]:
# computes the sum of gradients of given tensors w.r.t. graph leaves
out.backward()

In [28]:
x.grad

tensor([[101., 101.],
        [101., 101.]])

### Simple autograd example - Regression

In [29]:
# Input feature vector

x = [1., 2., 3., 4., 5.]

In [30]:
# Target variables

y = [10., 20., 30., 40., 50.]

In [31]:
# Weight / Bias

w = Variable(torch.tensor([1.]), requires_grad=True)

<center><img src="img/linear-regression-graph.png" width="600"></center>

In [32]:
# training iterations

for epoch in range(5):
    
    for x_i, y_i in zip(x, y):
        
        # compute predicted target variable
        y_pred = x_i * w
                
        # compute Mean Squared Error (MSE)
        loss = (y_pred - y_i) ** 2
        
        # compute gradients
        loss.backward()
        
        print('\t x={x_i}, y={y_i}, w.grad={w.grad[0]}'.format(**locals()))
        
        # make one step towards the local minima, with learning rate 0.01
        w.data -= 0.01 * w.grad.data
        
        # clear gradients after updating weights
        w.grad.data.zero_()
        
    print('Loss at epoch #%d: %.6f \n' % (epoch+1, loss.data[0]))

print('Final: w = %.4f' % w.data)

	 x=1.0, y=10.0, w.grad=-18.0
	 x=2.0, y=20.0, w.grad=-70.55999755859375
	 x=3.0, y=30.0, w.grad=-146.0592041015625
	 x=4.0, y=40.0, w.grad=-212.92185974121094
	 x=5.0, y=50.0, w.grad=-226.22947692871094
Loss at epoch #1: 511.797760 

	 x=1.0, y=10.0, w.grad=-4.524589538574219
	 x=2.0, y=20.0, w.grad=-17.73638916015625
	 x=3.0, y=30.0, w.grad=-36.71432876586914
	 x=4.0, y=40.0, w.grad=-53.521331787109375
	 x=5.0, y=50.0, w.grad=-56.866416931152344
Loss at epoch #2: 32.337894 

	 x=1.0, y=10.0, w.grad=-1.1373271942138672
	 x=2.0, y=20.0, w.grad=-4.458320617675781
	 x=3.0, y=30.0, w.grad=-9.228721618652344
	 x=4.0, y=40.0, w.grad=-13.45343017578125
	 x=5.0, y=50.0, w.grad=-14.294281005859375
Loss at epoch #3: 2.043265 

	 x=1.0, y=10.0, w.grad=-0.2858867645263672
	 x=2.0, y=20.0, w.grad=-1.1206741333007812
	 x=3.0, y=30.0, w.grad=-2.3197975158691406
	 x=4.0, y=40.0, w.grad=-3.381744384765625
	 x=5.0, y=50.0, w.grad=-3.5931015014648438
Loss at epoch #4: 0.129104 

	 x=1.0, y=10.0, w.grad=

### Linear Regression using PyTorch

The diabetes dataset consists of 10 physiological variables (age, sex,
weight, blood pressure) measure on 442 patients, and an indication of
disease progression after one year

* **Samples total** - 442
* **Dimensionality** - 10
* **Features** - real, -.2 < x < .2
* **Targets** - integer 25 - 346

##### Load dataset from scikit-learn

In [33]:
from sklearn import datasets

# http://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html
diabetes = datasets.load_diabetes()

X = diabetes.data[:]
y = diabetes.target[:].reshape(-1,1)

### Define Neural Network class

In [34]:
from torch import nn

In [35]:
class LinearRegressionModel(nn.Module):
    """
    Define Linear Regression class
    """

    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__() 
        self.linear = nn.Linear(input_dim, output_dim)  # neural network with 1 layer

    def forward(self, x):
        return self.linear(x)

In [36]:
# instantiate Linear Regression

model = LinearRegressionModel(10, 1)

In [37]:
# define loss functions - Mean Square Error (MSE)

criterion = nn.MSELoss() # (y_hat − y)^2,

In [38]:
# define learning rate

lr = 0.5

# define parameter optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=lr)

In [39]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1113,  0.2761, -0.1605,  0.0476,  0.2351, -0.1523, -0.0477, -0.1117,
          -0.1829,  0.0904]], requires_grad=True), Parameter containing:
 tensor([-0.0175], requires_grad=True)]

### Main training loop

In [40]:
n_epochs = 1000

for epoch in range(n_epochs):
    
    # convert features and target into PyTorch Variable
    inputs = Variable(torch.from_numpy(X).float())
    targets = Variable(torch.from_numpy(y).float())

    # forward pass
    outputs = model.forward(inputs)

    # calculate loss (MSE)
    loss = criterion(outputs, targets)
    
    # compute gradients
    loss.backward()
    
    # perform one step in the oposite direction to the gradient (update weights)
    optimizer.step()
    
    # clear gradient values after weights are updated
    optimizer.zero_grad()
    
    if epoch % 100 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 29080.962890625
epoch 100, loss 3935.114501953125
epoch 200, loss 3407.6298828125
epoch 300, loss 3194.447998046875
epoch 400, loss 3079.576904296875
epoch 500, loss 3009.974609375
epoch 600, loss 2966.006591796875
epoch 700, loss 2937.71337890625
epoch 800, loss 2919.281494140625
epoch 900, loss 2907.143310546875


### Measure accuracy

In [41]:
# switch to evaluation mode

model = model.eval()

In [42]:
# predict target variable for the whole dataset

with torch.no_grad():
    y_pred = model.forward(Variable(torch.from_numpy(X).float()))
    y_pred = y_pred.data.numpy()

In [43]:
from sklearn.metrics import r2_score

# calculate variance score
r2_score(y, y_pred)

0.5111097216523584